export interface GalleryImage {
  src: string;
  alt: string;
  category: string;
  title: string;
}

export const CATEGORIES = [
  { id: "all", label: "All Photos" },
  { id: "exterior", label: "Exterior & Views" },
  { id: "rooms", label: "Suites & Rooms" },
  { id: "dining", label: "Dining & Breakfast" },
  { id: "spa", label: "Spa & Pool" },
  { id: "prayer", label: "Prayer Room" },
  { id: "local", label: "Ulcinj & Surroundings" },
] as const;

export type CategoryId = (typeof CATEGORIES)[number]["id"];

export const galleryImages: GalleryImage[] = [
  { src: "/images/gallery/hotel-maghrib-gallery-01.webp", alt: "Hotel Maghrib exterior building facade in Ulcinj Montenegro", category: "exterior", title: "Hotel Exterior" },
  { src: "/images/gallery/hotel-maghrib-gallery-02.webp", alt: "Panoramic Adriatic sea view from Hotel Maghrib balcony Ulcinj", category: "exterior", title: "Adriatic Panorama" },
  { src: "/images/gallery/hotel-maghrib-gallery-03.webp", alt: "Sunset over Adriatic Sea viewed from Hotel Maghrib terrace", category: "exterior", title: "Sunset Over Adriatic" },
  { src: "/images/gallery/hotel-maghrib-gallery-04.webp", alt: "Hotel Maghrib swimming pool and sun loungers Ulcinj", category: "spa", title: "Swimming Pool" },
  { src: "/images/gallery/hotel-maghrib-gallery-05.webp", alt: "Indoor pool and jacuzzi at Hotel Maghrib spa wellness center", category: "spa", title: "Indoor Pool & Jacuzzi" },
  { src: "/images/gallery/hotel-maghrib-gallery-06.webp", alt: "Hotel Maghrib sauna room with wooden interior", category: "spa", title: "Sauna Room" },
  { src: "/images/gallery/hotel-maghrib-gallery-07.webp", alt: "Whirlpool jacuzzi with chromotherapy lights at Hotel Maghrib spa", category: "spa", title: "Jacuzzi Spa" },
  { src: "/images/gallery/hotel-maghrib-gallery-08.webp", alt: "Hotel Maghrib pool area with children wading pool", category: "spa", title: "Kids Pool Area" },
  { src: "/images/gallery/hotel-maghrib-gallery-09.webp", alt: "Deluxe double bedroom with sea view balcony at Hotel Maghrib", category: "rooms", title: "Deluxe Double Room" },
  { src: "/images/gallery/hotel-maghrib-gallery-10.webp", alt: "Spacious family suite with separate lounge area Hotel Maghrib Ulcinj", category: "rooms", title: "Family Suite Lounge" },
  { src: "/images/gallery/hotel-maghrib-gallery-11.webp", alt: "Premium king bedroom with panoramic sea view Hotel Maghrib", category: "rooms", title: "Premium King Room" },
  { src: "/images/gallery/hotel-maghrib-gallery-12.webp", alt: "Superior triple room with three beds and sea view Hotel Maghrib", category: "rooms", title: "Superior Triple Room" },
  { src: "/images/gallery/hotel-maghrib-gallery-13.webp", alt: "Modern bathroom with rain shower at Hotel Maghrib Ulcinj", category: "rooms", title: "Suite Bathroom" },
  { src: "/images/gallery/hotel-maghrib-gallery-14.webp", alt: "Hotel Maghrib room interior with elegant furnishings and sea view", category: "rooms", title: "Elegant Room Interior" },
  { src: "/images/gallery/hotel-maghrib-gallery-15.webp", alt: "Private balcony with sea view seating at Hotel Maghrib Montenegro", category: "rooms", title: "Private Sea-View Balcony" },
  { src: "/images/gallery/hotel-maghrib-gallery-16.webp", alt: "Hotel Maghrib room with Qibla direction marker and prayer mat", category: "prayer", title: "Qibla Direction in Room" },
  { src: "/images/gallery/hotel-maghrib-gallery-17.webp", alt: "Halal breakfast buffet spread at Hotel Maghrib sea view terrace", category: "dining", title: "Halal Breakfast Buffet" },
  { src: "/images/gallery/hotel-maghrib-gallery-18.webp", alt: "Fresh pastries and traditional dishes at Hotel Maghrib breakfast", category: "dining", title: "Fresh Pastries & Traditional Dishes" },
  { src: "/images/gallery/hotel-maghrib-gallery-19.webp", alt: "Hotel Maghrib dining terrace overlooking Adriatic Sea Ulcinj", category: "dining", title: "Sea-View Dining Terrace" },
  { src: "/images/gallery/hotel-maghrib-gallery-20.webp", alt: "Coffee and tea setup on Hotel Maghrib breakfast buffet", category: "dining", title: "Breakfast Beverages" },
  { src: "/images/gallery/hotel-maghrib-gallery-21.webp", alt: "Fresh fruits and healthy options at Hotel Maghrib halal breakfast", category: "dining", title: "Fresh Fruits & Healthy Options" },
  { src: "/images/gallery/hotel-maghrib-gallery-22.webp", alt: "Hotel Maghrib prayer room Musalla with Qibla direction", category: "prayer", title: "On-Site Prayer Room" },
  { src: "/images/gallery/hotel-maghrib-gallery-23.webp", alt: "Wudu facilities at Hotel Maghrib prayer room", category: "prayer", title: "Wudu Facilities" },
  { src: "/images/gallery/hotel-maghrib-gallery-24.webp", alt: "Hotel Maghrib restaurant interior with elegant halal dining setup", category: "dining", title: "Restaurant Interior" },
  { src: "/images/gallery/hotel-maghrib-gallery-25.webp", alt: "Hotel Maghrib lobby and reception area Ulcinj Montenegro", category: "exterior", title: "Hotel Lobby & Reception" },
  { src: "/images/gallery/hotel-maghrib-gallery-26.webp", alt: "Hotel Maghrib hallway corridor with modern design", category: "exterior", title: "Hotel Corridor" },
  { src: "/images/gallery/hotel-maghrib-gallery-27.webp", alt: "Mala Plaza Small Beach near Hotel Maghrib Ulcinj Montenegro", category: "local", title: "Small Beach (Mala Plaza)" },
  { src: "/images/gallery/hotel-maghrib-gallery-28.webp", alt: "Pine trees Boric forest next to Hotel Maghrib Ulcinj coast", category: "local", title: "Pine Forest (Boric)" },
  { src: "/images/gallery/hotel-maghrib-gallery-29.webp", alt: "Ulcinj Old Town fortress view from Hotel Maghrib area", category: "local", title: "Ulcinj Old Town" },
  { src: "/images/gallery/hotel-maghrib-gallery-30.webp", alt: "Velika Plaza Long Beach Ulcinj near Hotel Maghrib", category: "local", title: "Long Beach (Velika Plaza)" },
  { src: "/images/gallery/hotel-maghrib-gallery-31.webp", alt: "Adriatic coast sunset from Hotel Maghrib hilltop location", category: "exterior", title: "Hilltop Sunset View" },
  { src: "/images/gallery/hotel-maghrib-gallery-32.webp", alt: "Hotel Maghrib exterior at golden hour with warm lighting", category: "exterior", title: "Golden Hour Exterior" },
  { src: "/images/gallery/hotel-maghrib-gallery-33.webp", alt: "Hotel Maghrib night view with illuminated building and pool", category: "exterior", title: "Night View" },
  { src: "/images/gallery/hotel-maghrib-gallery-34.webp", alt: "Hotel Maghrib room desk and work area with sea view", category: "rooms", title: "Room Desk Area" },
  { src: "/images/gallery/hotel-maghrib-gallery-35.webp", alt: "Hotel Maghrib bedroom with king size bed and luxury bedding", category: "rooms", title: "King Bedroom" },
  { src: "/images/gallery/hotel-maghrib-gallery-36.webp", alt: "Hotel Maghrib suite living room with comfortable seating", category: "rooms", title: "Suite Living Area" },
  { src: "/images/gallery/hotel-maghrib-gallery-37.webp", alt: "Hotel Maghrib children play area and family facilities", category: "spa", title: "Children's Area" },
  { src: "/images/gallery/hotel-maghrib-gallery-38.webp", alt: "Hotel Maghrib rooftop terrace with panoramic Adriatic views", category: "exterior", title: "Rooftop Terrace" },
  { src: "/images/gallery/hotel-maghrib-gallery-39.webp", alt: "Hotel Maghrib spa treatment room with massage bed", category: "spa", title: "Spa Treatment Room" },
  { src: "/images/gallery/hotel-maghrib-gallery-40.webp", alt: "Hotel Maghrib halal breakfast omelette and egg station", category: "dining", title: "Omelette Station" },
  { src: "/images/gallery/hotel-maghrib-gallery-41.webp", alt: "Traditional Balkan pastries at Hotel Maghrib halal breakfast", category: "dining", title: "Traditional Balkan Pastries" },
  { src: "/images/gallery/hotel-maghrib-gallery-42.webp", alt: "Hotel Maghrib swimming pool with children section and loungers", category: "spa", title: "Pool & Loungers" },
  { src: "/images/gallery/hotel-maghrib-gallery-43.webp", alt: "Hotel Maghrib parking area with free private parking for guests", category: "exterior", title: "Free Private Parking" },
  { src: "/images/gallery/hotel-maghrib-gallery-44.webp", alt: "Ada Bojana island beach near Hotel Maghrib Ulcinj Montenegro", category: "local", title: "Ada Bojana Island" },
  { src: "/images/gallery/hotel-maghrib-gallery-45.webp", alt: "Valdanos olive grove bay near Hotel Maghrib Ulcinj coast", category: "local", title: "Valdanos Olive Grove" },
  { src: "/images/gallery/hotel-maghrib-gallery-46.webp", alt: "Hotel Maghrib reception staff welcoming Muslim family guests", category: "exterior", title: "Hotel Reception" },
  { src: "/images/gallery/hotel-maghrib-gallery-47.webp", alt: "Hotel Maghrib luggage storage and concierge service area", category: "exterior", title: "Concierge Service" },
  { src: "/images/gallery/hotel-maghrib-gallery-48.webp", alt: "Hotel Maghrib building surrounded by Mediterranean pine trees", category: "exterior", title: "Hotel Amidst Pine Trees" },
  { src: "/images/gallery/hotel-maghrib-gallery-49.webp", alt: "Hotel Maghrib guest room smart TV and modern amenities", category: "rooms", title: "In-Room Smart TV" },
  { src: "/images/gallery/hotel-maghrib-gallery-50.webp", alt: "Hotel Maghrib spa relaxation area with loungers and quiet ambiance", category: "spa", title: "Spa Relaxation Area" },
  { src: "/images/gallery/hotel-maghrib-gallery-51.webp", alt: "Hotel Maghrib swimsuit dryer and pool towel service", category: "spa", title: "Pool Towel Service" },
  { src: "/images/gallery/hotel-maghrib-gallery-52.webp", alt: "Hotel Maghrib corridor with modern lighting and elegant design", category: "exterior", title: "Elegant Corridor" },
  { src: "/images/gallery/hotel-maghrib-gallery-53.webp", alt: "Hotel Maghrib breakfast terrace with panoramic Adriatic sea view", category: "dining", title: "Breakfast Terrace Panorama" },
  { src: "/images/gallery/hotel-maghrib-gallery-54.webp", alt: "Hotel Maghrib room mini bar with halal certified refreshments", category: "rooms", title: "Halal Minibar" },
  { src: "/images/gallery/hotel-maghrib-gallery-55.webp", alt: "Hotel Maghrib key card and welcome amenities for guests", category: "rooms", title: "Welcome Amenities" },
  { src: "/images/gallery/hotel-maghrib-gallery-56.webp", alt: "Hotel Maghiri modern bathroom with premium toiletries and towels", category: "rooms", title: "Premium Bathroom" },
  { src: "/images/gallery/hotel-maghrib-gallery-57.webp", alt: "Ulcinj Marina and boat harbor near Hotel Maghrib Montenegro", category: "local", title: "Ulcinj Marina" },
  { src: "/images/gallery/hotel-maghrib-gallery-58.webp", alt: "Hotel Maghrib staff team photo welcoming Muslim guests to Ulcinj", category: "exterior", title: "Hotel Maghrib Team" },
];
